name: Release
on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: read

jobs:
  build:
    name: Build example-mui
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - run: npm ci

      - run: npm run build

      - run: mkdir out && cp -R packages/mui-example/dist/ out/mui-example && cp -R packages/ionic-example/dist/ out/ionic-example

      - name: Archive
        run: tar --dereference --hard-dereference --directory out -cvf artifact.tar .

      - name: Upload
        uses: actions/upload-artifact@main
        with:
          name: github-pages
          path: ./artifact.tar
          if-no-files-found: warn

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
